;; -*- flycheck-disabled-checkers: (emacs-lisp emacs-lisp-checkdoc) -*-

(require 'prelude-c)
(require 'prelude-clojure)
(require 'prelude-common-lisp)
(require 'prelude-company)
(require 'prelude-css)
(require 'prelude-emacs-lisp)
(require 'prelude-js)
(require 'prelude-lisp)
(require 'prelude-lsp)
(require 'prelude-perl)
(require 'prelude-python)
(require 'prelude-racket)
(require 'prelude-ruby)
(require 'prelude-rust)
(require 'prelude-scheme)
(require 'prelude-shell)
(require 'prelude-ts)
(require 'prelude-vertico)
(require 'prelude-web)
(require 'prelude-xml)
(require 'prelude-yaml)

(provide 'prelude-modules)
